/**
 * @fileoverview gRPC-Web generated client stub for blog
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.4
// source: blog.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.blog = require('./blog_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.blog.BlogRunTimeClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.blog.BlogRunTimePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.blog.BlogRuntimeRequest,
 *   !proto.blog.BlogRuntimeResponse>}
 */
const methodDescriptor_BlogRunTime_UpdateBlog = new grpc.web.MethodDescriptor(
  '/blog.BlogRunTime/UpdateBlog',
  grpc.web.MethodType.UNARY,
  proto.blog.BlogRuntimeRequest,
  proto.blog.BlogRuntimeResponse,
  /**
   * @param {!proto.blog.BlogRuntimeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.blog.BlogRuntimeResponse.deserializeBinary
);


/**
 * @param {!proto.blog.BlogRuntimeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.blog.BlogRuntimeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.blog.BlogRuntimeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.blog.BlogRunTimeClient.prototype.updateBlog =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/blog.BlogRunTime/UpdateBlog',
      request,
      metadata || {},
      methodDescriptor_BlogRunTime_UpdateBlog,
      callback);
};


/**
 * @param {!proto.blog.BlogRuntimeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.blog.BlogRuntimeResponse>}
 *     Promise that resolves to the response
 */
proto.blog.BlogRunTimePromiseClient.prototype.updateBlog =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/blog.BlogRunTime/UpdateBlog',
      request,
      metadata || {},
      methodDescriptor_BlogRunTime_UpdateBlog);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.blog.GetBlogRequest,
 *   !proto.blog.BlogRuntimeResponse>}
 */
const methodDescriptor_BlogRunTime_GetBlogg = new grpc.web.MethodDescriptor(
  '/blog.BlogRunTime/GetBlogg',
  grpc.web.MethodType.UNARY,
  proto.blog.GetBlogRequest,
  proto.blog.BlogRuntimeResponse,
  /**
   * @param {!proto.blog.GetBlogRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.blog.BlogRuntimeResponse.deserializeBinary
);


/**
 * @param {!proto.blog.GetBlogRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.blog.BlogRuntimeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.blog.BlogRuntimeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.blog.BlogRunTimeClient.prototype.getBlogg =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/blog.BlogRunTime/GetBlogg',
      request,
      metadata || {},
      methodDescriptor_BlogRunTime_GetBlogg,
      callback);
};


/**
 * @param {!proto.blog.GetBlogRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.blog.BlogRuntimeResponse>}
 *     Promise that resolves to the response
 */
proto.blog.BlogRunTimePromiseClient.prototype.getBlogg =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/blog.BlogRunTime/GetBlogg',
      request,
      metadata || {},
      methodDescriptor_BlogRunTime_GetBlogg);
};


module.exports = proto.blog;

